### ISSUE TITLE
该AC机无法在洛咕上提交。

### ISSUE THREAD

**Issue by Fedoraer** [Polaris1949/OISol#1]
洛咕无耻地屏蔽了'/tmp'关键字。
只需要小小的改动即可。

**Comment by signron** [comment]
So how to change it

**Comment by Fedoraer** [comment]
Remove all string '/tmp' and use something instead.

**Comment by signron** [comment]
well。。then how to use it

**Comment by lin714093880** [comment]
我也想知道怎么用

**Comment by moesoha** [comment]
洛咕观光团

![1j7_vw_8j50mp0o_rx_0o4](https://user-images.githubusercontent.com/5895757/44298228-cf26d400-a311-11e8-9440-d974a254e6ff.gif)

**Comment by cnyali-lk** [comment]
我也想无耻的问一下怎么用

**Comment by happyZYM** [comment]
我想无耻的问一下怎么用

**Comment by memset0** [comment]
我也想无耻的问一下怎么用

**Comment by fsy2018** [comment]
属于作弊行为 后来者早点退了吧

**Comment by memset0** [comment]
~~我只是复读机~~

**Comment by AndrewWayne** [comment]
无耻地问下怎么用

**Comment by rourou365** [comment]
我也想无耻的问一下怎么用

**Comment by abc1763613206** [comment]
我也想无耻的问一下怎么用

**Comment by signron** [comment]
luogu......

**Comment by Fedoraer** [comment]
What is Happening...
Wow!

**Comment by Fedoraer** [comment]
原理：容器内只有"/tmp"目录可以写入。
所以所有文件（包括输入输出，源代码和编译后的可执行文件）都只能放在 /tmp 目录下。
我们只要在该目录下检索所有".in"做后缀名的文件与标准输入比对，再把该文件扩展名改为".out"输出即可。

使用方法：
直接提交 OISol/luogu/dev/baka.cpp 即可。（当前需要去掉 "/tmp"字符，我们正在修改。）

注：使用该源代码可能导致封号GG.所以建议使用小号提交并开启”完全隐私保护“。

**Comment by lin714093880** [comment]
@Fedoraer 你要不再试试?

技术还可以，以后注意提高下自己的人品和道德。

**Comment by Himself65** [comment]
@lin714093880 
您已经把他封了，让人家怎么试（

**Comment by abc1763613206** [comment]
## 您大概可以当评测员了

**Comment by memset0** [comment]
@Himself65 ~~开个小号不就可以试了~~

**Comment by memset0** [comment]
@Fedoraer 您有没有发现来这里的一半是管理员一半是吃瓜群众。。。

**Comment by goldimax** [comment]
看來以後洛谷要把ans文件放在容器外了……

**Comment by Polaris1949** [comment]
This was just for fun. It will be no longer maintained.

**Comment by Polaris1949** [comment]
Do ***NOT*** abuse it for anything.

**Comment by FCBM71** [comment]
**S**mart **B**oy

**Comment by signron** [comment]
23333333333333
